# yamllint disable rule:line-length
---
name: write-to-file

description: |
  Writes op-value from 1password to out-file.

  op-value format = vault/item/field.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: .

  op-value:
    description: E.g., vault-name/item-name/field-name
    required: true

  out-file:
    description: output file name
    required: true

runs:
  using: "composite"

  steps:
  
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo "op://${{ inputs.op-value }}" > ${{ inputs.out-file }}.tpl

    - shell: bash
      run: op inject -i ${{ inputs.out-file }}.tpl -o ${{ inputs.out-file }}
