# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: integration tests

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

permissions:
  contents: read

jobs:

  integration-tests:
    name: 1password-action integration tests
    runs-on: ubuntu-latest

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@c6cd5d8b7c1d1d65d6224134e67e30d06b374917         # v4.1.5

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f      # v1.0.0
        with:
          version: 2.27.0

      - name: write value using 1password-action/write-to-file
        uses: ThoughtWorks-DPS/1password-action/write-to-file@main
        with:
          op-value: empc-lab/svc-gmail/username
          out-file: write_test.txt

      - name: test 1password-action/write-to-file results
        shell: bash
        run: |
          set -exo pipefail
          cat write_test.txt | grep "twdps"

      - name: populate template with 1password-action/tpl using defaults
        uses: ThoughtWorks-DPS/1password-action/tpl@main
        with:
          tpl-file: default_email.txt
          before-tpl: echo "before tpl message"
          after-tpl: echo "after tpl message"

      - name: test 1password-action/tpl with defaults results
        shell: bash
        run: |
            set -exo pipefail
            cat default_email.txt | grep "twdps"

      - name: populate template with 1password-action/tpl using overrides
        uses: ThoughtWorks-DPS/1password-action/tpl@main
        with:
          tpl-path: test
          tpl-file: email.txt
          tpl-ext: template
          out-path: .
          out-file: named_email.txt

      - name: test 1password-action/tpl using overrides results
        shell: bash
        run: |
            set -exo pipefail
            cat named_email.txt | grep "twdps"

      - name: source $GITHUB_ENV from file using 1password-action/env
        uses: ThoughtWorks-DPS/1password-action/env@main
        with:
          env-file: test/op.env

      - name: test 1password-action/env results
        shell: bash
        run: |
            set -exo pipefail
            echo $GMAIL_ADDRESS | grep "twdps"
