# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: release version

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

permissions:
  contents: write
  issues: write

jobs:

  release-version:
    name: release version
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/release-version.yaml@421a368581ea29881a5d70ef1744d90d874c5703    # v0.1.0

  on-success:
    name: notify new release version
    if: success()
    runs-on: ubuntu-latest

    steps:

      - name: Load slack webhook
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SLACK_WEBHOOK_TYPE: op://empc-lab/svc-slack/lab-events

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "New release: ThoughtWorks-DPS/1password-action ${{ github.ref_name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      # - name: Notify empc teams
      #   uses: slackapi/slack-github-action@v1.26.0
      #   with:
      #     channel-id: 'leb-events'
      #     slack-message: 'New release: ThoughtWorks-DPS/1password-action ${{ github.ref_name }}'
      #   env:
      #     SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN

      # - name: Notify empc teams
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: lab-events
      #     SLACK_MESSAGE: 'New release: ThoughtWorks-DPS/1password-action ${{ github.ref_name }}'
      #     SLACK_WEBHOOK: $SLACK_WEBHOOK
