# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: release version

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

permissions:
  contents: write
  issues: write

jobs:

  publish-version:
    name: publish semantic release version of action
    runs-on: ubuntu-latest

    steps:
      - name: publish semantic release version from tag
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=${{ github.sha }}
          gh release create "${{ github.ref_name }}" \
             --repo="${{ github.repository }}" \
             --title="${{ github.ref_name }}, SHA ${{ github.sha }}" \
             --generate-notes --notes "SHA ${SHA:0:40}"
